name=NeoStreaming
version=1.0.1
author=Nerdsiah
maintainer=Nerdsiah
sentence=A fully fuctional, Zero-Heap C++ Streaming Library for Embedded Systems.
paragraph=Implements a Zero-Heap Proxy Pattern for C++ style stream manipulation (<<, setw, setprecision, fixed, hexfloat, etc.) without the memory fragmentation of the Arduino String class.
category=Data Processing
url=https://github.com/Nerdsiah/NeoStreaming
architectures=*
includes=NeoStreaming.h
